### ISSUE TITLE
BufferGeometryExporter

### ISSUE THREAD

**Issue by mrdoob** [jamieowen/threeflow.js#2]
This is great stuff!! Can't wait to mess with this at some point :)

However, before you get too deep in the `Geometry` handling, I would suggest to try handling `BufferGeometry` first as we're slowly transitioning to that geometry structure.

More info here:
https://github.com/mrdoob/three.js/issues/4386

Some resources:
https://github.com/mrdoob/three.js/blob/master/src/core/Projector.js#L316-L377
https://github.com/mrdoob/three.js/blob/master/examples/js/BufferGeometryUtils.js

**Comment by jamieowen** [comment]
Cheers @mrdoob, much appreciated!

Thanks for the info on the BufferGeometry. I've just added an exporter for this now..
Here's a quick test render :
https://github.com/jamieowen/threeflow.js/blob/master/examples/renders/geometry_buffer.png

This is just geometry for now, not vertex colours. I don't think Sunflow actually supports per-vertex colours, just per-face shaders. So will have to select just 1 vertex as the face shader colour.

Also can you point me in the right direction for any BufferGeometry class using attributes.index if you have any? ( I haven't tested that yet ).

And just in the process of sorting out an npm package for installation :)

Cheers!

**Comment by mrdoob** [comment]
Sweet!

Here's some code that parses `attributes.index`:
https://github.com/mrdoob/three.js/blob/master/src/core/Projector.js#L339-L367

**Comment by mrdoob** [comment]
Ah wait, maybe you mean an example that uses attributes.index...
http://threejs.org/examples/webgl_buffergeometry.html

**Comment by jamieowen** [comment]
Nice one.. Works a treat!

**Comment by mrdoob** [comment]
Yay! ^^

**Comment by jamieowen** [comment]
Hey @mrdoob,

Just reopened this for a quick question... I've just released a first version of this a couple of days ago,
With support for textures and bump maps.. Getting some pretty decent renders out of it :)

Would be good to get your feedback on it.. I'm a bit unsure about extending the three material class though. It feels a bit "intrusive", especially if you had an existing three.js scene and wanted a quick render. So i'll probably change that next..

Anyway.. With the new BufferGeometry format, will it be storing face normals as well? Or just vertex normals? And then what happens to FaceMaterials?! 

Also, I had a few ideas on integrating this ( or other renderers i.e. [LuxRender](http://www.luxrender.net/) )into the three.js editor.. Is the right place to post them on the three.js issues?

Cheers!

**Comment by mrdoob** [comment]
It's looking great! :)

> I'm a bit unsure about extending the three material class though. It feels a bit "intrusive", especially if you had an existing three.js scene and wanted a quick render. So i'll probably change that next..

Yeah, we were tinkering with a raytracer recently:
https://www.youtube.com/watch?v=CutAKGWaEBE
http://alteredqualia.com/three/examples/raytracer_sandbox_reflection.html

And I realised that the current materials weren't good enough. Maybe an approach could be to create `MeshRaytracingMaterial` which would extend `MeshPhongMaterial` and add properties like `reflection`, `refraction`, etc... What other properties do you need?

> Anyway.. With the new BufferGeometry format, will it be storing face normals as well? Or just vertex normals?

No. Only vertex normals.

> And then what happens to FaceMaterials?!

Still trying to figure this one out...

> Also, I had a few ideas on integrating this ( or other renderers i.e. LuxRender )into the three.js editor.. Is the right place to post them on the three.js issues?

Yup! :)

**Comment by ghost** [comment]
The Luxrender renderer would be amazing

Am also thinking about using this for Photogammetry projects.
