### ISSUE TITLE
What is this?

### ISSUE THREAD

**Issue by herkyl** [jamieowen/threeflow.js#3]
There are pretty pictures but no text, what exactly is threeflow? Is it some kind of fork of three.js?

**Comment by andrevenancio** [comment]
So Three.js gives you the ability to render 3D in your browser right? There is a little thing called sunflow (http://sunflow.sourceforge.net/). This allows you to render it with better quality. So you can do several stuff with this:
a) create something in code and have a big resolution image being printed into a poster.
b) have an animation on 3D and render several frames and do a movie or something...

Whatever your imagination leads you to.

**Comment by jamieowen** [comment]
Hey @herkyl,
It's not a fork of three.js, and it doesn't give you super-duper rendering in the browser!

It uses the sunflow renderer, which is a open source renderer written in java. This type of renderer is not for real-time graphics.  But for realistic renders with accurate lighting and what not.

threeflow takes a three.js scene and converts in into a sunflow scene file (.sc file). Then passes it via a socket to a node server that then saves the file and spawns the sunflow java app.

Here's a screenshot that might make more sense:
https://raw.github.com/jamieowen/threeflow.js/master/screenshot.jpg

So like @andrevenancio said, you can do what you want with the render! 

I'm in the process of creating an npm package so people can try it out.. so it's not complete yet...
