### ISSUE TITLE
The default settings don't produce the same quality of output as the cached versions

### ISSUE THREAD

**Issue by webprofusion-chrisc** [jamieowen/threeflow.js#7]
Awesome app! I now have a real world use for a ThreeJS to Raytracing workflow and came across threeflow. When firing up the app (in this case on windows 10 64-bit) and hitting render on any of the examples the default output is a little blocky compared to the default example rendering, it's not obvious what setting should be changed to improve that (regardless of how it affects speed)?

**Comment by jamieowen** [comment]
Thanks man! A bit of a slow reply but here goes...

It can be a bit of an art getting good quality renders, I could only suggest reading some of the links referenced at the bottom of the documentation.

Also, I'm not really working on this project anymore - it was a bit of fun to see if it would work! The Sunflow renderer this uses is also a bit outdated.  

For open source renderers I would investigate something like http://www.luxrender.net/en_GB/index

Or if you need to render Three.js scenes I would look into exporting data as OBJ or perhaps use https://clara.io/ - which I think supports importing three.js scenes as json..

**Comment by webprofusion-chrisc** [comment]
Thanks, I think I need to investigate the clara.io option a bit more.
